<div id="news">
	<h3>News and Announcements</h3>
	<dl>
		<dt>May 6 2010</dt>
		<dd>Hypertable selected for the conference program at Berlin Buzzwords 2010<br/>June 7th & 8th 2010, <a href="http://www.berlinbuzzwords.de/">Berlin Buzzwords 2010»</a> Berlin, Germany</dd>
	</dl>
	<dl>
		<dt>May 19 2010</dt>
		<dd>Hypertable selected for the conference program at NoSQL Frankfurt<br/>September 28th 2010, <a href="http://sites.google.com/site/nosqlfrankfurt/">NoSQL Frankfurt»</a> Goethe University Frankfurt, Germany</dd>
	</dl>
</div><!-- news -->
