<div id="news">
	<h3>News and Announcements</h3>
	<dl>
		<dt>Jun 24 2010</dt>
		<dd>Hypertable delivers up to 1000% performance improvement over HBase, <a href="http://blog.hypertable.com/?p=14">Hypertable vs. HBase Performance Evaluation»</a></dd>
	</dl>
	<dl>
		<dt>May 19 2010</dt>
		<dd>Hypertable selected for the conference program at NoSQL Frankfurt<br/>September 28th 2010, <a href="http://sites.google.com/site/nosqlfrankfurt/">NoSQL Frankfurt»</a> Goethe University Frankfurt, Germany</dd>
	</dl>
</div><!-- news -->
