<div id="news">
	<h3>News and Announcements</h3>
	<dl>
		<dt>Oct 17 2010</dt>
		<dd>Doug Judd will present <a href="http://www.meetup.com/cloudcomputing/calendar/14362435/">Database Architectures and Hypertable</a> at the Silicon Valley Cloud Computing Group Meetup, October 21st 2010<br> Fenwick & West, Mountain View, CA</dd>
	</dl>
	<dl>
		<dt>Sep 23 2010</dt>
		<dd>Doug Judd will present <a href="http://internet-briefing.ch/nosql">NoSQL Databases Demystified</a> at the Internet Briefing<br>October 5th 2010, Z&uuml;rich, Switzerland</dd>
	</dl>

</div><!-- news -->




