<div id="footer-container">
	<div id="footer">
		<p class="nav">
			<a href="about.html">About</a> |
			<a href="download.html">Download</a> |
			<a href="license.html">License</a> |
			<a href="documentation.html">Documentation</a> |
			<a class="external" href="http://code.google.com/p/hypertable/issues/list">Bug Tracker</a> |
			<a href="mailing-list.html">Mailing Lists</a> |
			<a href="sponsors.html">Sponsors</a> |
			<a href="feedback.html">Feedback</a> |
			<a href="sitemap.html">Sitemap</a>
		</p>
		<!-- . nav -->
		<p class="copy">Copyright 2008 Hypertable. All rights reserved. Design by <a href="http://www.bluecoastweb.com" target="_blank">Blue Coast Web</a></p>
		<ul>
			<li class="first"><span>Sponsors:</span></li>
			<li><a href="sponsors.html#zvents"><img src="images/lgo-zvents.gif" alt="Zvents" /></a></li>
			<li><a href="sponsors.html#baidu"><img src="images/lgo-baidu.gif" alt="Baidu" /></a></li>
		</ul>
	</div><!-- footer -->
</div><!-- footer-container -->
<!-- generated on <?= date("r") ?> -->
