<div id="news">
	<h3>News and Announcements</h3>
	<dl>
		<dt>June 22 2009</dt>
		<dd><a href="sponsors.html#rediff">Rediff.com</a> becomes an official sponsor of the Hypertable project. Thanks! »</dd>
	</dl>
	<dl>
		<dt>February 9 2009</dt>
		<dd>O'Reilly Velocity has selected Hypertable for the 2009 Conference Program<br/>June 22 - 24, <a href="http://en.oreilly.com/velocity2009">Velocity 2009»</a> San Jose, CA</dd>
	</dl>
</div><!-- news -->
