<div id="news">
	<h3>News and Announcements</h3>
	<dl>
		<dt>January 12 2009</dt>
		<dd><a href="http://www.baidu.com/">Baidu</a> becomes an official sponsor of the Hypertable project. Thanks Baidu! »</dd>
	</dl>
	<dl>
		<dt>November 21 2008</dt>
		<dd>Hypertable presentation at the QCon San Francisco 2008 Conference<br/>November 21st, <a href="http://qconsf.com/sf2008/">QCon San Francisco 2008</a>, San Francisco, CA »</</dd>
	</dl>
</div><!-- news -->
